import './base'
import './component/app'
import './component/main'
import './component/side'
import './component/tab'
import './component/home'
import './component/forms'
import './component/animations'
import './component/pull_hook'
import './component/dialogs'
import './component/buttons'
import './component/carousel'
import './component/infinite_scroll'
import './component/load_more'
import './component/lazy_repeat'
import './component/progress'
import './component/transition'

F.build(document.body);
